spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: -1 #单个文件的大小 不限制
      max-request-size: -1  #单次请求的文件的总大小 不限制
thymeleaf:
  prefix: classpath:/templates/
  mode: XHTML
  encoding: UTF-8
  content-type: text/html
  cache: false

#mybatis:
#  mapper-locations: classpath*:mapper/*.xml # mapper映射文件位置
#  type-aliases-package: com.example.trade.entity # 实体类所在的位置

mybatis-plus:
  #配置mapper扫描
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.trade.entity
  typeEnumsPackage: com.example.trade.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: oracle
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

student:
  name: mawendy
  sex: male
  age: 20
  home: anhui
  education: master
  tutor: Liu
  major: mechanics
  school: mecahnical engineering


