server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 300m
spring:
  datasource:
    username: root
    password: 52wendyma
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.68.139:3306/springstudent?serverTimezone=GMT%2B8
    initialSize: 5
    minIdle: 5
    maxActive: 200

  ##########################  文件路径配置  ##########################
project-url:
  path: D:/zhangyue/upload/
  url: http://localhost:8882

  ##########################  日志路径配置  ##########################
log:
  level: info
  path: d:/log/demoLogs