server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 300m
spring:
  application:
    name: ma8080
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: root
          password: 52wendyma
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://175.24.68.139:3306/springstudent?serverTimezone=GMT%2B8
          initialSize: 5
          minIdle: 5
          maxActive: 20
        slave_1:
          username: root
          password: 52wendyma
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://175.24.68.139:3306/springstudent?serverTimezone=GMT%2B8
          initialSize: 5
          minIdle: 5
          maxActive: 20
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2

  ##########################  文件路径配置  ##########################
project-url:
  path: D:/zhangyue/upload/
  url: http://localhost:8882

  ##########################  日志路径配置  ##########################
log:
  level: info
  path: d:/log/demoLogs